id: I742A499C
legacy_id: P000312
ocr_import_info:
  bdrc_scan_id: W23794
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T14:57:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:45:50.323244+00:00'
last_modified: 2022-09-02 12:45:55.931701
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23794
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23794
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཤེས་པའི་འཕྲིན་ཡིག་གི་ཊཱི་ཀ
  author: ངག་གི་དབང་ཕྱུག་དགེ་ལེགས་རྒྱ་མཚོའི་སྡེ།
statistics: null
quality: null
bases:
  I2772:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2772
      total_pages: 266
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2772.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
